pipeline {
    agent any
    stages {
        stage('build application') {
            steps {
                sh 'mvn -f java-tomcat-sample/pom.xml clean package'
            }
            post {
                success {
                    echo 'Now archiving artifact..'
                    archiveArtifacts artifacts: '**/*.war'
                }
            }
        }
        stage('Deploy in staging Env') {
            steps {
                build job: 'Deploy_Application_Staging_Env'
            }
        }
    }
}
